#!/usr/bin/env bash
#
# termbin-nc - Upload stdin to termbin.com using netcat
#
# Copyright (C) 2026 develarmy.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#

set -o errexit
set -o nounset
set -o pipefail

readonly PROGRAM_NAME="termbin-nc"
readonly VERSION="1.2 beta"
readonly HOST="termbin.com"
readonly PORT="9999"

print_help() {
    cat <<EOF
Usage: $PROGRAM_NAME [OPTION]...

Upload text received from standard input to $HOST and print the resulting URL.

Options:
  -h, --help       display this help and exit
      --version    output version information and exit

Examples:
  lsusb | $PROGRAM_NAME
      Upload the output of lsusb.

  journalctl -b | $PROGRAM_NAME
      Upload the current boot log.

  cat file.txt | $PROGRAM_NAME
      Upload the contents of file.txt.

  $PROGRAM_NAME < file.txt
      Upload a file using standard input.

  printf 'Hello, world!\\n' | $PROGRAM_NAME
      Upload text generated by printf.

The program connects to $HOST on TCP port $PORT using netcat (nc).

Input:
  Data must be provided through standard input. Command-line arguments
  are not accepted, except for the options listed above.

Exit status:
  0    successful completion
  1    upload failed
  2    invalid command-line usage
  127  netcat (nc) is not installed

Copyright:
  Copyright (C) 2026 develarmy.org

License:
  GNU General Public License version 3 or later.

Report bugs:
  <https://develarmy.org/>
EOF
}

print_version() {
    printf '%s %s\n' "$PROGRAM_NAME" "$VERSION"
}

print_usage_error() {
    printf '%s: %s\n' "$PROGRAM_NAME" "$1" >&2
    printf "Try '%s --help' for more information.\n" "$PROGRAM_NAME" >&2
}

# Parse command-line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            print_help
            exit 0
            ;;

        --version)
            print_version
            exit 0
            ;;

        --)
            shift
            break
            ;;

        -*)
            print_usage_error "unrecognized option '$1'"
            exit 2
            ;;

        *)
            print_usage_error "extra operand '$1'"
            exit 2
            ;;
    esac
done

if [[ $# -gt 0 ]]; then
    print_usage_error "extra operand '$1'"
    exit 2
fi

# Check whether netcat is installed
if ! command -v nc >/dev/null 2>&1; then
    printf '%s: error: command not found: nc\n' "$PROGRAM_NAME" >&2
    printf '%s: install netcat before using this program\n' "$PROGRAM_NAME" >&2
    exit 127
fi

# Upload standard input to termbin.com
if ! nc "$HOST" "$PORT"; then
    printf '%s: error: upload failed\n' "$PROGRAM_NAME" >&2
    exit 1
fi
